#!/bin/bash
source helper_functions

DEBUG=$1
OUTPUT_DIR=$2
INPUT_DIR=$3
IMAGE_TYPE=$4
PROCESS=$5
PATH_TO_IMAGES=$6
NUM_PATHS=$7
WORKFLOW=$8
BAND_PAN=$9
BAND_BLUE=$10
BAND_GREEN=$11
BAND_RED=$12
BAND_NIR=$13
BAND_CA=$14
BAND_RE=$15
BAND_SWIR=$16

PATH_TO_IMAGES=$( echo $PATH_TO_IMAGES | tr "%" " ")

if [ $DEBUG = "d" ]; then
    get_debug "add band math start values"
fi

# Loop to print image names and number of bands in image for user
count=0
for file in $PATH_TO_IMAGES;
do
    count=$((count+1))
    num_bands=$( otbcli_ReadImageInfo -in $file | grep -e 'Number of bands' | cut -d" " -f5 )
    filename=$( echo $file |rev | cut -d"/" -f1 | rev )
    echo Image $count: $filename / $num_bands bands
done

# If more than one image to process ask
if [ $NUM_PATHS -gt 1 ]; then
    echo
    echo Would you like to add a different expression string for every image??
    echo
    echo Type Y or N
    echo
    read add_diff_exp
else
    add_diff_exp="N"
fi

# If adding a different band math expression to create layer for every image
#    then set varibale add_diff_exp to "Y"
if [ $add_diff_exp = "Y" ] || [ $add_diff_exp = "y" ];
then
    add_diff_exp="Y"
else
    # If adding the same band math expression to every image then store
    #    the expression string in the variable, expression
    echo
    echo Give me your expression string to add to every file.
    echo
    echo EXAMPLE: im1b1+im1b2
    echo
    read expression
fi

# Loop through the image paths to add a layer tp each image
for file in $PATH_TO_IMAGES;
do
    # Get full_filename with extension
    full_filename=$( echo $file | rev | cut -d"/" -f1 | rev )
    # Get filename without extension
    filename=$( echo $full_filename | rev | cut -d"." -f2 | rev)
    # If adding a different expression string to every file
    #    collect expression string for every image in the loop
    if [ $add_diff_exp = "Y" ];
    then
	echo
	echo "FOR FILE:"
	echo $full_filename
	echo
	echo "Give me your expression string."
	echo
	echo "EXAMPLE: im1b1+im1b2"
	echo "EXAMPLE: cos(im1b1)>cos(im2b1)?im3b1:im3b2"
    echo
	read expression
    fi

    # Create the new single band image with wanted expression
    otbcli_BandMath -il $PATH_TO_IMAGES -out $OUTPUT_DIR/$filename-bm.tif \
	-exp $expression

    # Concatonate single band image to original image
    otbcli_ConcatenateImages -il $file $OUTPUT_DIR/$filename-bm.tif \
	-out $OUTPUT_DIR/$filename-BM.tif

done

# If original images are not stored in the output directory then do not remove
#    the images on complettion 
if [[ $PATH_TO_IMAGES =~ $OUTPUT_DIR ]]; then
    rm $PATH_TO_IMAGES
fi

if [ $DEBUG = "d" ]; then
    get_debug "add band math end values"
fi
