#!/bin/bash

DEBUG=$1
OUTPUT_DIR=$2
IMAGE_TYPE=$3
PROCESS=$4
PATH_TO_IMAGES=$5
NUM_PATHS=$6
WORKFLOW=$7

PATH_TO_IMAGES=$( echo $PATH_TO_IMAGES | tr "%" " ")

if [ $DEBUG = "d" ]; then
    echo $OUTPUT_DIR
    echo $IMAGE_TYPE
    echo $PROCESS
    echo $PATH_TO_IMAGES
    echo $NUM_PATHS
    echo $WORKFLOW
    echo band math start values
    read sodcosh
fi

echo
echo HOW MANY SINGLE BAND IMAGES WOULD YOU LIKE TO MAKE?
echo
echo TYPE A NUMBER
echo
read num_images_to_make

# Loop to create the number of single band images as stored in the 
#   variable $num_images_to_make
for ((i = 0 ; i < $num_images_to_make ; i++)); do
    # Display all the files in the input directory along with the file 
    #    number and the number of bands in each file so they can easily
    #    make an expression string
    clear
    count=0
    for file in $PATH_TO_IMAGES;
    do
	count=$((count+1))
	num_bands=$( otbcli_ReadImageInfo -in $file | grep -e 'Number of bands' | cut -d" " -f5 )
	filename=$( echo $file | rev | cut -d"/" -f1 | rev )
	echo Image $count: $filename / $num_bands bands
    done
    # Create filename for current single band image
    filename="$IMAGE_TYPE-IMAGE_$i-BM.tif"
    # Ask user for the expression string for this single band image
    echo GIVE ME YOUR EXPRESSION STRING
    echo
    echo "EXAMPLE: cos( im1b1 ) > cos( im2b1 ) ? im3b1 : im3b2"
    echo
    read expression
    # Create the new single band image with wanted expression
    otbcli_BandMath -il $PATH_TO_IMAGES -out $OUTPUT_DIR/$filename \
    -exp $expression
done

# If original images are not stored in the output directory then do not remove
#    the images on completion
if [[ $PATH_TO_IMAGES =~ $OUTPUT_DIR ]]; then
    rm $PATH_TO_IMAGES
fi

if [ $DEBUG = "d" ]; then
    echo $OUTPUT_DIR
    echo $IMAGE_TYPE
    echo $PROCESS
    echo $PATH_TO_IMAGES
    echo $NUM_PATHS
    echo $WORKFLOW
    echo band math end values
    read sodcosh
fi
