#!/bin/bash

clear				# clear terminal window
echo ============================================================================
echo ENTORNO AUTOMATIZADO DE GEOPROCESAMIENTO: TELEDETECCION, SIG Y MODELAMIENTO
echo Bienvenido, $USER!		# dollar sign is used to get content of variable
echo
pause
clear
echo ============================================================================
echo ENTORNO AUTOMATIZADO DE GEOPROCESAMIENTO: TELEDETECCION, SIG Y MODELAMIENTO
echo "***************************************************************"
echo "* @source   : AUTOMATED GEOPROCESSING - IMAGE_MASTER          *"
echo "* @tool     : VHR RESULTION IMAGE PROCESSING                  *"
echo "* @autor    : CHRISTOPHER Turner                              *"
echo "* @e-mail   : CLTURNER23@gmail.com                            *"
echo "* @revision : 0.0 - 29/11/2018                                *"
echo "* ............................................................*"
echo "***************************************************************"
echo
echo "WHAT TYPE OF IMAGE WOULD YOU LIKE TO PROCESS"
echo "1. PERU SAT"
echo "2. DIGITAL PLANET"
echo "3. WORLDVIEW"
echo
echo "Choose and image type and press [ENTER]:"
read choice
echo ============================================================================

if [ $choice -eq 1 ]
then
   echo 'Great! we will process a PERU SAT IMAGE!'
   echo
   echo "Please give me the path/to/the/image!"
   read PATH_TO_IMAGE
   echo Your image path is: $PATH_TO_IMAGE
   echo
   echo "Please give me output directory for your files!"
   read OUTPUT_DIR
   echo Your output directory is: $OUTPUT_DIR
   echo
   peru_sat $PATH_TO_IMAGE $OUTPUT_DIR
   echo
else 
 if [ $choice -eq 2 ]
 then
   echo 'Great! we will process a DIGITAL PLANET image!'
   echo
   echo "Please give me the path/to/the/image!"
   read PATH_TO_IMAGE
   echo Your image path is: $PATH_TO_IMAGE
   echo
   echo "Please give me output directory for your files!"
   read OUTPUT_DIR
   echo Your output directory is: $OUTPUT_DIR
   echo
   digital_planet $PATH_TO_IMAGE $OUTPUT_DIR
   echo
 else 
  if [ $choice -eq 3 ]
  then
   echo 'Great! we will process a WORLDVIEW image!'
   echo
   echo "Please give me the path/to/the/image!"
   read PATH_TO_IMAGE
   echo Your image path is: $PATH_TO_IMAGE
   echo
   echo "Please give me output directory for your files!"
   read OUTPUT_DIR
   echo Your output directory is: $OUTPUT_DIR
   echo
   worldview $PATH_TO_IMAGE $OUTPUT_DIR
   echo
  fi
 fi  	
fi

