#!/bin/bash
source helper_functions

DEBUG=$1
OUTPUT_DIR=$2
INPUT_DIR=$3
IMAGE_TYPE=$4
PROCESS=$5
PATH_TO_IMAGES=$6
NUM_PATHS=$7
WORKFLOW=$8
BAND_PAN=$9
BAND_BLUE=$10
BAND_GREEN=$11
BAND_RED=$12
BAND_NIR=$13
BAND_CA=$14
BAND_RE=$15
BAND_SWIR=$16

PROCESS=$( echo $PROCESS | tr "%" " " )
PATH_TO_IMAGES=$( echo $PATH_TO_IMAGES | tr "%" " " )

if [ $DEBUG = "d" ]; then
    get_debug "starting multiprocess"
fi

get_num_paths () {
    char="%"
    NUM_PATHS=$( echo "${PATH_TO_IMAGES}" | awk -F"${char}" '{print NF-1}' )
    NUM_PATHS=$((NUM_PATHS+1))
}

get_file_names () {
    if [ ! -d "$INPUT_DIR" ] && [ "$2" = 1 ]; then
	directory_or_paths=$PATH_TO_IMAGES
    else
	if [ -d "$INPUT_DIR" ] && [ $2 = 1 ]; then
	    directory_or_paths=$(cd "$INPUT_DIR" && pwd)
	elif [ $2 > 1 ]; then
	    directory_or_paths=$(find "$OUTPUT_DIR" -maxdepth 1 -type d)
	else
	    echo "Soemthing went very wrong...Sorry"
	fi
    fi
    new_PATH_TO_IMAGES=""
    if [ -d "$directory_or_paths" ]; then
	for file in "$directory_or_paths"/*; do
	    if [ $num -eq 9 ] && [[ $file  =~ ".zip" ]]; then
		new_PATH_TO_IMAGES="$new_PATH_TO_IMAGES $file_dir$file"
            elif [[ $file =~ ".tif" && ${file} != *"tif."* ]]; then
		new_PATH_TO_IMAGES="$new_PATH_TO_IMAGES $file_dir$file"
            elif [[ $file =~ ".jp2" ]]; then
		new_PATH_TO_IMAGES="$new_PATH_TO_IMAGES $file_dir$file"
            fi
	done
    else
	for file in $directory_or_paths; do
	    if [ $num -eq 9 ] && [[ $file  =~ ".zip" ]]; then
	    	new_PATH_TO_IMAGES="$new_PATH_TO_IMAGES $file_dir$file"
            elif [[ $file =~ ".tif" && ${file} != *"tif."* ]]; then
            	new_PATH_TO_IMAGES="$new_PATH_TO_IMAGES $file_dir$file"
            elif [[ $file =~ ".jp2" ]]; then
            	new_PATH_TO_IMAGES="$new_PATH_TO_IMAGES $file_dir$file"
            fi
	done
    fi
    PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
}

# Count the number of process entered into the process string
count=0
for num in $PROCESS;
do
    count=$((count+1))
done

# Set process string values to the corresponding automated workflow
if [ "$count" -eq 1 ] && [ "$PROCESS" -eq 11 ] # Then this is a workflow without ROI extraction
then
    if [ $IMAGE_TYPE = "PSAT" ]; then
	WORKFLOW=11
	PROCESS="7 1 4 6"
    elif [ $IMAGE_TYPE = "WVIW" ]; then
	WORKFLOW=11
        PROCESS="7 6"
    elif [ $IMAGE_TYPE = "PLNT" ]; then
	WORKFLOW=11
	PROCESS="9 7 1 4 6"
    fi
elif [ "$count" -eq 1 ] && [ "$PROCESS" -eq 12 ]
then
    if [ $IMAGE_TYPE = "PSAT" ] || [ $IMAGE_TYPE = "WVIW" ]; then
	WORKFLOW=12 # Then this is a workflow with ROI extraction
	PROCESS="7 8 1 4 6"
    elif [ $IMAGE_TYPE = "PLNT" ]; then
	WORKFLOW=12
	PROCESS="9 7 8 1 4 6"
    fi
else
    PROCESS=$PROCESS
fi

count=0
for num in $PROCESS;
do
    count=$((count+1))
    if [ "$num" = 1 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
	get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES 
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
	./radiometric_indices "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 2 ]; then
	PROCESS=$( echo $PROCESS | tr " " "%" )
	get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
        if [ $DEBUG = "d" ]; then
	    get_debug
	fi
	./add_band_math "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 3 ]
    then
        PROCESS=$( echo $PROCESS | tr " " "%" )
        get_file_names $OUTPUT_DIR $count
        get_num_paths $PATH_TO_IMAGES
        PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
	if [ $DEBUG = "d" ]; then
	    get_debug "passing to band math $num in $PROCESS"
	fi
	./band_math "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 4 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
	get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
	if [ $DEBUG = "d" ]; then
	    get_debug "passing to remove band"
	fi
	./remove_band "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 5 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
	get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
	if [ $DEBUG = "d" ]; then
	    get_debug "passing to concatonate"
	fi
	./concatonate "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 6 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
        get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )

	if [ $DEBUG = "d" ]; then
	    get_debug "passing to lsms"
	fi
        ./large_scale_mean_shift "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 7 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
        get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	if [ $DEBUG = "d" ]; then
	    get_debug "Doing mosaic $num in $PROCESS"
	fi
        ./mosaic "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 8 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
	get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
	if [ $DEBUG = "d" ]; then
	    get_debug "Doing extract_roi $num in $PROCESS"
	fi
	./extract_roi "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 9 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
        get_file_names $OUTPUT_DIR $count
	get_num_paths $PATH_TO_IMAGES
	PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
	if [ $DEBUG = "d" ]; then
	    get_debug "passing to unzip"
	fi
	./unzip_files "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    elif [ "$num" = 10 ]
    then
	PROCESS=$( echo $PROCESS | tr " " "%" )
        get_file_names $OUTPUT_DIR $count
        get_num_paths $PATH_TO_IMAGES
        PATH_TO_IMAGES=$( echo $new_PATH_TO_IMAGES | tr " " "%" )
        if [ $DEBUG = "d" ]; then
            get_debug "Doing cloud detect $num in $PROCESS"
        fi
	./cloud_detector "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
    else
	echo no process for that number
    fi
done
