#!/bin/bash

echo
echo ============================================================================
echo WELCOME TO PROCESSING FOR PERU SAT IMAGES
echo ============================================================================
echo
echo ===== Segmantation and Classification of image at: =========================
echo "$1"
image=$1
output_dir=$2
echo ============================================================================
echo
echo CHOOSE YOUR VALUES FOR MeanShiftSmoothing
echo Example: for -spatialr 5, -ranger 10, -thres 0.1, -maxiter 100
echo Enter: 5 10 0.1 100
read MSS_vars
MSS_spatialr=$(echo $MSS_vars | cut -f1 -d " ")
MSS_ranger=$(echo $MSS_vars | cut -f2 -d " ")
MSS_thres=$(echo $MSS_vars | cut -f3 -d " ")
MSS_maxiter=$(echo $MSS_vars | cut -f4 -d " ")
echo
echo YOUR MeanShiftSmoothing FLAGS ARE:
echo -spatialr $MSS_spatialr, -ranger $MSS_ranger, -thres $MSS_thres, -maxiter $MSS_maxiter
echo
echo ============================================================================
echo
echo CHOOSE YOUR VALUES FOR LSMSSegmentation
echo Example: for -spatialr 10, -ranger 15, -minsize 25
echo Enter: 10 15 25
read LSMSSeg_vars
SEG_spatialr=$(echo $LSMSSeg_vars | cut -f1 -d " ")
SEG_ranger=$(echo $LSMSSeg_vars | cut -f2 -d " ")
SEG_minsize=$(echo $LSMSSeg_vars | cut -f3 -d " ")
echo
echo YOUR LSMSSegmentation FLAGS ARE:
echo -spatialr $SEG_spatialr -ranger $SEG_ranger -minsize $SEG_minsize
echo
echo ============================================================================
echo
echo CHOOSE YOUR VALUES FOR LSMSSmallRegionsMerging
echo Example: for -minsize 10
echo Enter: 10
read LSMS_srm
SRM_minsize=$(echo $LSMS_srm | cut -f1 -d " ")
echo
echo Your LSMSSmallRegionsMerging flags are:
echo -minsize $SRM_minsize
echo
echo ============================================================================
# Build file names
filename=PSat_MSS_$MSS_spatialr-$MSS_ranger-$MSS_thres-$MSS_maxiter-SEG_$SEG_spatialr-$SEG_ranger-$SEG_minsize-SRM-$SRM_minsize.tif
filename_shp=PSatMSS_$MSS_spatialr-$MSS_ranger-$MSS_thres-$MSS_maxiter-SEG_$SEG_spatialr-$SEG_ranger-$SEG_minsize-SRM-$SRM_minsize.shp
filename_raster=PSatMSS_$MSS_spatialr-$MSS_ranger-$MSS_thres-$MSS_maxiter-SEG_$SEG_spatialr-$SEG_ranger-$SEG_minsize-SRM-$SRM_minsize-raster.tif
filename_binary=PSatMSS_$MSS_spatialr-$MSS_ranger-$MSS_thres-$MSS_maxiter-SEG_$SEG_spatialr-$SEG_ranger-$SEG_minsize-SRM-$SRM_minsifilename-binary.tif
# Build output folder name 
output_folder=/PSatMSS_$MSS_spatialr-$MSS_ranger-$MSS_thres-$MSS_maxiter-SEG_$SEG_spatialr-$SEG_ranger-$SEG_minsize-SRM-$SRM_minsize
output_dir=$output_dir$output_folder
mkdir $output_dir
echo ============================================================================
echo REMOVING BLUE BAND FROM Peru Sat IMAGE
remove_blue_band $image $output_dir
image1=$output_dir/b2_3_4_ndvi_image.tif
echo BLUE BAND REMOVED
echo YOUR NEW IMAGE IS: $output_dir/b2_3_4_ndvi_image.tif
echo ============================================================================
echo BEGINNIG SEGMENTATION

otbcli_MeanShiftSmoothing -in $image1 -fout smooth.tif -foutpos smooth_pos.tif \
    -spatialr $MSS_spatialr \
    -ranger $MSS_ranger \
    -thres $MSS_thres \
    -maxiter $MSS_maxiter \
    -modesearch 0

otbcli_LSMSSegmentation -in smooth.tif -inpos smooth_pos.tif -out init_seg.tif uint32 \
    -spatialr $SEG_spatialr \
    -ranger $SEG_ranger \
    -minsize $SEG_minsize \
    -tilesizex 500 \
    -tilesizey 500

otbcli_LSMSSmallRegionsMerging -in smooth.tif -inseg init_seg.tif -out final_seg.tif uint32 \
    -minsize $SRM_minsize \
    -tilesizex 500 \
    -tilesizey 500

echo ============================================================================
echo VECTORIZING!!!
echo image1 is: $image1
otbcli_LSMSVectorization -in $image1 -inseg final_seg.tif -out $output_dir/$filename_shp
echo ============================================================================

echo ============================================================================
echo RASTERIZING

otbcli_Rasterization -in $output_dir/$filename_shp \
    -epsg 32719 \
    -background 0 \
    -mode attribute \
    -mode.attribute.field meanB3 \
    -spx 0.7 \
    -spy 0.7 \
    -out $output_dir/$filename_raster
echo ============================================================================

echo ENTER A THRESHHOLD VALUE
echo example 0.62
read threshhold
exp_string="im1b1>$threshhold?1:254"
echo $exp_string
otbcli_BandMath -il $output_dir/$filename_raster -out $output_dir/$filename_binary -exp $exp_string

rm final_seg.tif init_seg.tif  smooth.tif smooth_pos.tif
rm $output_dir/b2_3_4_ndvi_image.tif
