#!/bin/bash
source helper_functions

DEBUG=$1
OUTPUT_DIR=$2
INPUT_DIR=$3
IMAGE_TYPE=$4
PROCESS=$5
PATH_TO_IMAGES=$6
NUM_PATHS=$7
WORKFLOW=$8
BAND_PAN=$9
BAND_BLUE=$10
BAND_GREEN=$11
BAND_RED=$12
BAND_NIR=$13
BAND_CA=$14
BAND_RE=$15
BAND_SWIR=$16

PATH_TO_IMAGES=$( echo $PATH_TO_IMAGES | tr % " ")

if [ $DEBUG = "d" ]; then
    get_debug "Starting radiometric indices"
fi

full_indices_list=""
function get_indice () {
    # Choose the radiometric Indices to add to each file
    full_indices_list=""
    echo
    echo Choose your Radiometric Indice:
    echo "1. Vegetation:NDVI    7. Vegetation:MSAVI2             13. Water:NDWI   19.Soil:BI"
    echo "2. Vegetation:TNDVI   8. Vegetation:GEMI               14. Water:NDWI2  20.Soil:BI2"
    echo "3. Vegetation:RVI     9. Vegetation:IPVI               15. Water:MNDWI  21.BuiltUp:ISU"
    echo "4. Vegetation:SAVI   10. Vegetation:LAIFromNDVILog     16. Water:NDTI"
    echo "5. Vegetation:TSAVI  11. Vegetation:LAIFromReflLinear  17. Soil:RI"
    echo "6. Vegetation:MSAVI  12. Vegetation:LAIFromNDVIFormo   18. Soil:CI"
    echo
    echo EXAMPLE: 1 12 20
    echo
    read index_numbers
    for num in $index_numbers; do
	case $num in
	    1) full_indices_list+="Vegetation:NDVI ";;
	    2) full_indices_list+="Vegetation:TNDVI ";;
	    3) full_indices_list+="Vegetation:RVI ";;
	    4) full_indices_list+="Vegetation:SAVI ";;
	    5) full_indices_list+="Vegetation:TSAVI ";;
	    6) full_indices_list+="Vegetation:MSAVI ";;
	    7) full_indices_list+="Vegetation:MSAVI2 ";;
	    8) full_indices_list+="Vegetation:GEMI ";;
	    9) full_indices_list+="Vegetation:IPVI ";;
	    10) full_indices_list+="Vegetation:LAIFromNDVILog ";;
	    11) full_indices_list+="Vegetation:LAIFromReflLinear ";;
	    12) full_indices_list+="Vegetation:LAIFromNDVIFormo ";;
	    13) full_indices_list+="Water:NDWI ";;
	    14) full_indices_list+="Water:NDWI2 ";;
	    15) full_indices_list+="Water:MNDWI ";;
	    16) full_indices_list+="Water:NDTI ";;
	    17) full_indices_list+="Soil:RI ";;
	    18) full_indices_list+="Soil:CI ";;
	    19) full_indices_list+="Soil:BI ";;
	    20) full_indices_list+="Soil:BI2 ";;
	    21) full_indices_list+="BuiltUp:ISU ";;
	    *)
		echo $num " is not a choice in the list [press enter]"
		read
		get_indice
		;;
	esac
    done
}

if [ $WORKFLOW -eq 11 ] || [ $WORKFLOW -eq 12 ];
then
    # If the process is an automated workflow
    # Do not add different values to each file
    # Retrive the automated values from text file: planet_mines_roads_deforestation_values
    add_diff_indices="N"
    if [ $IMAGE_TYPE = "PLNT" ]; then
	full_indices_list=$( sed -n '1p' < planet-mines_roads_deforestation_values )
    elif [ $IMAGE_TYPE = "PSAT" ]; then
	full_indices_list=$( sed -n '1p' < psat-mines_roads_deforestation_values )
    elif [ $IMAGE_TYPE = "WVIW" ]; then
	full_indices_list=$( sed -n '1p' < wview-mines_roads_deforestation_values )
    fi
    full_indices_list=$( echo $full_indices_list | cut -d"-" -f2 )
else
    # Choose if you want to add different radiometric indices to each file
    if [ $NUM_PATHS -gt 1 ]; then
	echo
	echo Would you like to add a different radiometric index to each file?
	echo
	echo Type Y or N
	echo
	read add_diff_indices
    else
	add_diff_indices="N"
    fi

    if [ $add_diff_indices = "Y" ] || [ $add_diff_indices = "y" ]
    then
	echo
	echo We will add radiometric indices for each file as we go.
	echo
    else
	# Choose the radiometric Indices to add to each file
	get_indice
    fi
fi

# Loop through all the files and add radiometric Indices
original_files_list=""
output_files_list=""
for file in $PATH_TO_IMAGES;
do
    # Get filename from file path and remove file extension
    full_filename=$( echo $file | rev | cut -d"/" -f1 | rev )
    filename=$( echo $full_filename | rev | cut -d"." -f2 | rev )
    # Make a " " dilimeted list of all original fill paths for removal
    #     after the loop has been completed
    original_files_list+=" "$file

    # If adding different Radiometrc Indices to every file choose them
    #    each time you loop
    if [ $add_diff_indices = "Y" ] || [  $add_diff_indices = "y" ]
    then
	get_indice
    fi

    # Create filename extension from all radiometric indices for this loop
    filename_addition=""
    for indice in $full_indices_list;
    do
	indice=$( echo $indice | cut -f2 -d":")
	filename_addition+="_"$indice
    done

    
    otbcli_RadiometricIndices -in $file -list $full_indices_list \
			      -channels.blue $BAND_BLUE \
			      -channels.green $BAND_GREEN \
			      -channels.red $BAND_RED \
			      -channels.nir $BAND_NIR \
			      -out $OUTPUT_DIR/radio.tif

    # Concatonate the new bands to the original file
    otbcli_ConcatenateImages -il \
	$file $OUTPUT_DIR/radio.tif \
	-out $OUTPUT_DIR/$filename-RI$filename_addition.tif

    # Remove the Radimetric Indices bads created before Concatonation
    #     with the original files
    rm $OUTPUT_DIR/radio.tif
done

# Remove the original files that do not include the requested Radiometric Indices
if [[ $PATH_TO_IMAGES =~ $OUTPUT_DIR ]]; then
    rm $original_files_list
fi

if [ $DEBUG = "d" ]; then
    get_debug "end radiometric Indices"
fi
